/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.billsystem;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author NEXT BOSS
 */
public class AdminDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminDashboard.class.getName());

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAddCustomer = new javax.swing.JButton();
        btnRemoveCustomer = new javax.swing.JButton();
        btnGenerateBill = new javax.swing.JButton();
        btnViewReport = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnSearchCustomer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 102));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setText("ADMIN DASHBOARD");

        btnAddCustomer.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 12)); // NOI18N
        btnAddCustomer.setText("Add Customer");
        btnAddCustomer.addActionListener(this::btnAddCustomerActionPerformed);

        btnRemoveCustomer.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 12)); // NOI18N
        btnRemoveCustomer.setText("Remove Customer");
        btnRemoveCustomer.addActionListener(this::btnRemoveCustomerActionPerformed);

        btnGenerateBill.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 12)); // NOI18N
        btnGenerateBill.setText("Generate Bill");
        btnGenerateBill.addActionListener(this::btnGenerateBillActionPerformed);

        btnViewReport.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 12)); // NOI18N
        btnViewReport.setText("View Monthly Report");
        btnViewReport.addActionListener(this::btnViewReportActionPerformed);

        btnLogout.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 12)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        btnSearchCustomer.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 12)); // NOI18N
        btnSearchCustomer.setText("Search Customer");
        btnSearchCustomer.addActionListener(this::btnSearchCustomerActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGenerateBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRemoveCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSearchCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(135, 135, 135))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRemoveCustomer)
                .addGap(12, 12, 12)
                .addComponent(btnGenerateBill)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearchCustomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogout)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustomerActionPerformed
        new AddCustomerForm().setVisible(true);
    }//GEN-LAST:event_btnAddCustomerActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
      new loginform().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnRemoveCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveCustomerActionPerformed

    
    String id = JOptionPane.showInputDialog(this, 
        "Enter Customer ID to delete:");
    
    if (id == null || id.trim().isEmpty()) {
        return;
    }
    
    id = id.trim();
    ArrayList<Customer> customers = FileManager.loadCustomers();
    
    boolean found = false;
    for (int i = 0; i < customers.size(); i++) {
        if (customers.get(i).getId().equals(id)) {
            customers.remove(i);
            found = true;
            break;
        }
    }
    
    if (found) {
        FileManager.saveAllCustomers(customers);
        JOptionPane.showMessageDialog(this, 
            "Customer Deleted Successfully!");
    } else {
        JOptionPane.showMessageDialog(this, 
            "Customer ID not found!");
    }

    }//GEN-LAST:event_btnRemoveCustomerActionPerformed

    private void btnGenerateBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateBillActionPerformed
    new GenerateBillForm().setVisible(true);
    }//GEN-LAST:event_btnGenerateBillActionPerformed

    private void btnViewReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewReportActionPerformed
         String searchMonth = JOptionPane.showInputDialog(
            this,
            "Enter Month:"
    );

    if (searchMonth == null ||
            searchMonth.trim().isEmpty()) {

        return;
    }

    ArrayList<Bill> bills = FileManager.loadBills();

    StringBuilder report = new StringBuilder();

    double totalRevenue = 0;

    boolean found = false;

    report.append("===== ")
            .append(searchMonth.toUpperCase())
            .append(" REPORT =====\n\n");

    for (Bill bill : bills) {

        if (bill.getMonth().equalsIgnoreCase(searchMonth)) {

            found = true;

            report.append("Bill ID: ")
                    .append(bill.getBillId())
                    .append("\n");

            report.append("Customer ID: ")
                    .append(bill.getCustomerId())
                    .append("\n");

            report.append("Units: ")
                    .append(bill.getUnitsConsumed())
                    .append("\n");

            report.append("Amount: Rs. ")
                    .append(bill.calculateBill())
                    .append("\n");

            report.append("Status: ");

            if (bill.isPaid()) {

                report.append("PAID");
            }

            else {

                report.append("UNPAID");
            }

            report.append("\n\n");

            totalRevenue += bill.calculateBill();
        }
    }

    if (!found) {

        JOptionPane.showMessageDialog(this,
                "No bills found for this month!");

        return;
    }

    report.append("TOTAL REVENUE: Rs. ")
            .append(totalRevenue);

    JOptionPane.showMessageDialog(this,
            report.toString());
    }//GEN-LAST:event_btnViewReportActionPerformed

    private void btnSearchCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCustomerActionPerformed
        String customerId = JOptionPane.showInputDialog(
            this,
            "Enter Customer ID:"
    );

    if (customerId == null || customerId.trim().isEmpty()) {

        return;
    }

    ArrayList<Customer> customers =
            FileManager.loadCustomers();

    ArrayList<Bill> bills =
            FileManager.loadBills();

    Customer foundCustomer = null;

    // Search customer
    for (Customer c : customers) {

        if (c.getId().equals(customerId)) {

            foundCustomer = c;
            break;
        }
    }

    // Customer not found
    if (foundCustomer == null) {

        JOptionPane.showMessageDialog(this,
                "Customer not found!");

        return;
    }

    // Build report
    StringBuilder report = new StringBuilder();

    report.append("===== CUSTOMER DETAILS =====\n\n");

    report.append("Customer ID: ")
            .append(foundCustomer.getId())
            .append("\n");

    report.append("Name: ")
            .append(foundCustomer.getName())
            .append("\n");

    report.append("Address: ")
            .append(foundCustomer.getAddress())
            .append("\n");

    report.append("Contact: ")
            .append(foundCustomer.getContact())
            .append("\n\n");

    report.append("===== CUSTOMER BILLS =====\n\n");

    boolean hasBills = false;

    for (Bill bill : bills) {

        if (bill.getCustomerId().equals(customerId)) {

            hasBills = true;

            report.append("Bill ID: ")
                    .append(bill.getBillId())
                    .append("\n");

            report.append("Month: ")
                    .append(bill.getMonth())
                    .append("\n");

            report.append("Units: ")
                    .append(bill.getUnitsConsumed())
                    .append("\n");

            report.append("Amount: Rs. ")
                    .append(bill.calculateBill())
                    .append("\n");

            report.append("Status: ");

            if (bill.isPaid()) {

                report.append("PAID");
            }

            else {

                report.append("UNPAID");
            }

            report.append("\n\n");
        }
    }

    if (!hasBills) {

        report.append("No bills found.");
    }

    JOptionPane.showMessageDialog(this,
            report.toString());
    }//GEN-LAST:event_btnSearchCustomerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCustomer;
    private javax.swing.JButton btnGenerateBill;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRemoveCustomer;
    private javax.swing.JButton btnSearchCustomer;
    private javax.swing.JButton btnViewReport;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
