/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.billsystem;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author NEXT BOSS
 */
public class CustomerDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CustomerDashboard.class.getName());

    /**
     * Creates new form CustomerDashboard
     */
  
    private Customer customer;
    public CustomerDashboard(Customer customer) {
    initComponents();
    this.customer = customer;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnViewProfile = new javax.swing.JButton();
        btnViewBills = new javax.swing.JButton();
        btnPayBill = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel1.setText("CUSTOMER  DASHBOARD");

        btnViewProfile.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 12)); // NOI18N
        btnViewProfile.setText("View Profile ");
        btnViewProfile.addActionListener(this::btnViewProfileActionPerformed);

        btnViewBills.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 12)); // NOI18N
        btnViewBills.setText("View Bills");
        btnViewBills.addActionListener(this::btnViewBillsActionPerformed);

        btnPayBill.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 12)); // NOI18N
        btnPayBill.setText("Pay Bill");
        btnPayBill.addActionListener(this::btnPayBillActionPerformed);

        btnLogout.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 12)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnViewProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewBills, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPayBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnViewProfile)
                .addGap(18, 18, 18)
                .addComponent(btnViewBills)
                .addGap(18, 18, 18)
                .addComponent(btnPayBill)
                .addGap(18, 18, 18)
                .addComponent(btnLogout)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProfileActionPerformed
        JOptionPane.showMessageDialog(this,
        "Customer ID: " + customer.getId() +
        "\nName: " + customer.getName() +
        "\nAddress: " + customer.getAddress() +
        "\nContact: " + customer.getContact()
);
    }//GEN-LAST:event_btnViewProfileActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
       new loginform().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnPayBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayBillActionPerformed
String billId = JOptionPane.showInputDialog(
            this,
            "Enter Bill ID to Pay:"
    );

    if (billId == null || billId.trim().isEmpty()) {

        return;
    }

    ArrayList<Bill> bills = FileManager.loadBills();

    boolean found = false;

    for (Bill bill : bills) {

        // Customer can only pay own bills
        if (bill.getBillId().equals(billId)
                &&
                bill.getCustomerId().equals(customer.getId())) {

            found = true;

            if (bill.isPaid()) {

                JOptionPane.showMessageDialog(this,
                        "Bill already paid!");
            }

            else {

                bill.setPaid();

                FileManager.saveAllBills(bills);

                JOptionPane.showMessageDialog(this,
                        "Bill Paid Successfully!");
            }

            break;
        }
    }

    if (!found) {

        JOptionPane.showMessageDialog(this,
                "Bill not found!");
    }      
    
    }//GEN-LAST:event_btnPayBillActionPerformed

    private void btnViewBillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBillsActionPerformed
   ArrayList<Bill> allBills = FileManager.loadBills();

    // Filter bills for current customer
    StringBuilder report = new StringBuilder();
    report.append("===== YOUR BILLS =====\n\n");

    boolean found = false;

    for (Bill bill : allBills) {

        if (bill.getCustomerId().equals(customer.getId())) {

            found = true;

            report.append("Bill ID: ").append(bill.getBillId()).append("\n");
            report.append("Month: ").append(bill.getMonth()).append("\n");
            report.append("Units: ").append(bill.getUnitsConsumed()).append("\n");
            report.append("Amount: Rs. ").append(bill.calculateBill()).append("\n");
            report.append("Status: ").append(bill.isPaid() ? "PAID" : "UNPAID").append("\n");
            report.append("--------------------------\n");
        }
    }

    if (!found) {
        report.append("No bills found for your account.");
    }

    JOptionPane.showMessageDialog(this, report.toString());
    }//GEN-LAST:event_btnViewBillsActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPayBill;
    private javax.swing.JButton btnViewBills;
    private javax.swing.JButton btnViewProfile;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
